name: seno_card
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  flutter_quill: ^7.4.6
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/senocard-bg.png
    - assets/images/mood-1.png
    - assets/images/mood-2.png
    - assets/images/mood-3.png
    - assets/images/mood-4.png
    - assets/images/mood-5.png
    - assets/images/wave.png
    - assets/images/add-sign.png
    - assets/images/abu-belakang.png
    - assets/images/abu-depan.png
    - assets/images/biru-belakang.png
    - assets/images/biru-depan.png
    - assets/images/cream-belakang.png
    - assets/images/cream-depan.png
    - assets/images/merah-belakang.png
    - assets/images/merah-depan.png
    - assets/images/orange-belakang.png
    - assets/images/orange-depan.png
    - assets/images/logo.png
    - assets/images/google-logo.png

  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 200
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 600
    - family: AkayaTelivigala
      fonts:
        - asset: assets/fonts/AkayaTelivigala-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
